// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgmUEDmc6Ls0FP5hjVrg7F8TH4jaAZrsg',
    appId: '1:47281063166:android:d4dd10e41ae789ec0ad1af',
    messagingSenderId: '47281063166',
    projectId: 'laylah-cf6ac',
    storageBucket: 'laylah-cf6ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2qhHtxqT__bhwkAZKZpSrx35aBKviWE',
    appId: '1:47281063166:ios:b6ace8b67ae3c22e0ad1af',
    messagingSenderId: '47281063166',
    projectId: 'laylah-cf6ac',
    storageBucket: 'laylah-cf6ac.appspot.com',
    androidClientId: '47281063166-7gkdlpmsljdleju4s3aobr56ge23roue.apps.googleusercontent.com',
    iosClientId: '47281063166-653njs9qc4ud4a15ds69d79c929t68fd.apps.googleusercontent.com',
    iosBundleId: 'com.app.laylah',
  );
}
